# healthcare-system/config-repo/billing-service.yml
server:
  port: 8086 # Another different port

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:billingdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${AUTH_SERVER_JWKS_URI:http://auth-service:9000/oauth2/jwks}
spring.rabbitmq:
  host: ${RABBITMQ_HOST:rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER:guest}
  password: ${RABBITMQ_PASS:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

healthcare:
  amqp:
    # Ensure exchange name matches publisher (AppointmentService)
    exchange:
      appointments: healthcare.appointments.exchange
    # Define queue name and routing key this service uses
    queue:
      billing: billing-invoice-queue # Name of the queue for billing events
    routingkey:
      completed: appointment.completed

# Eureka client config inherited

logging:
  level:
    com.healthcare.billingservice: DEBUG
    org.hibernate.SQL: DEBUG