# config-server/src/main/resources/application.yml

spring:
  application:
    name: config-server
  profiles:
    active: git # Ensure git profile is active HERE
  cloud:
    config:
      server:
        git:
          # Define the URI directly in the internal config
          uri: file:///config-repo # Path inside the container where the volume is mounted
          # default-label: main # Optional here, can be in config-repo/config-server.yml
# The server port might also be better defined here initially
server:
  port: 8888

  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus # Add prometheus

# Optional: Eureka registration can also be defined here if not relying on config-repo/config-server.yml for it
# eureka:
#   client:
#     enabled: true
#     serviceUrl:
#       defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
#   instance:
#     prefer-ip-address: true