# healthcare-system/config-repo/medical-records-service.yml
server:
  port: 8085 # Yet another port

spring:
  # MongoDB Configuration
  data:
    mongodb:
      # Use environment variables or default to localhost for local runs
      # Use 'mongodb' service name when running in Docker Compose
      uri: mongodb://${MONGO_USER:user}:${MONGO_PASSWORD:password}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/${MONGO_DB:medicalrecordsdb}?authSource=admin
      # Example without auth: uri: mongodb://${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/${MONGO_DB:medicalrecordsdb}
      # Note: Adjust authSource if your user is defined in a different DB
      # auto-index-creation: true # Can be useful in dev, disable in prod for performance

# Eureka client config inherited

logging:
  level:
    com.healthcare.medicalrecordsservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG # Log MongoDB operations