version: '3.8'

services:
  # --- Database ---
  postgres-db:
    image: postgres:15 # Use a specific recent version
    container_name: postgres-db
    environment:
      POSTGRES_DB: servicedb_default # A default DB, services will use specific ones
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password # CHANGE THIS in a real scenario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare-network

  # --- Message Broker ---
  rabbitmq:
    image: rabbitmq:3.11-management # Use version with management UI
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest # CHANGE THIS for production
      RABBITMQ_DEFAULT_PASS: guest # CHANGE THIS for production
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - healthcare-network

  # --- Tracing Backend ---
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - healthcare-network

  # --- MongoDB (Optional - if needed by Medical Records Service later) ---
  # mongodb:
  #   image: mongo:6
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - healthcare-network

  # --- Monitoring (Optional - Add later if needed) ---
  # prometheus:
  #   ...
  # grafana:
  #   ...

# --- Volumes Definition ---
volumes:
  postgres_data:
  rabbitmq_data:
  # mongo_data:

# --- Network Definition ---
networks:
  healthcare-network:
    driver: bridge # Default Docker network driver